# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop_assistant design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import Qt



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1927, 1502)
        self.Frame = QtWidgets.QLabel(Form)
        self.Frame.setGeometry(QtCore.QRect(-50, -310, 2021, 1571))
        self.Frame.setMinimumSize(QtCore.QSize(1701, 0))
        self.Frame.setStyleSheet("")
        self.Frame.setText("")
        self.Frame.setPixmap(QtGui.QPixmap("Media/frame.png"))
        self.Frame.setScaledContents(True)
        self.Frame.setObjectName("Frame")


        self.date_box = QtWidgets.QLabel(Form)
        self.date_box.setGeometry(QtCore.QRect(110, 260, 311, 81))
        self.date_box.setText("")
        self.date_box.setPixmap(QtGui.QPixmap("Media/bar.png"))
        self.date_box.setScaledContents(True)
        self.date_box.setObjectName("date_box")


        self.temperature_box = QtWidgets.QLabel(Form)
        self.temperature_box.setGeometry(QtCore.QRect(110, 430, 311, 81))
        self.temperature_box.setText("")
        self.temperature_box.setPixmap(QtGui.QPixmap("Media/bar.png"))
        self.temperature_box.setScaledContents(True)
        self.temperature_box.setObjectName("temperature_box")


        self.arc_reactor = QtWidgets.QLabel(Form)
        self.arc_reactor.setGeometry(QtCore.QRect(550, 180, 821, 451))
        self.arc_reactor.setText("")
        self.arc_reactor.setPixmap(QtGui.QPixmap("Media/spin hud.gif"))
        self.arc_reactor.setScaledContents(True)
        self.arc_reactor.setObjectName("arc_reactor")

        self.movie = QMovie("./Media/spin hud.gif")
        self.arc_reactor.setMovie(self.movie)
        self.movie.start()


        self.ip_box = QtWidgets.QLabel(Form)
        self.ip_box.setGeometry(QtCore.QRect(110, 600, 311, 81))
        self.ip_box.setText("")
        self.ip_box.setPixmap(QtGui.QPixmap("Media/bar.png"))
        self.ip_box.setScaledContents(True)
        self.ip_box.setObjectName("ip_box")


        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1931, 1011))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("Media/bg.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")


        self.chat_box = QtWidgets.QLabel(Form)
        self.chat_box.setGeometry(QtCore.QRect(1500, 242, 350, 530))
        self.chat_box.setText("")
        self.chat_box.setPixmap(QtGui.QPixmap("Media/chatbox.png"))
        self.chat_box.setScaledContents(True)
        self.chat_box.setObjectName("chat_box")


        self.time_box = QtWidgets.QLabel(Form)
        self.time_box.setGeometry(QtCore.QRect(660, 700, 601, 121))
        self.time_box.setText("")
        self.time_box.setPixmap(QtGui.QPixmap("Media/bar 2.jpg"))
        self.time_box.setScaledContents(True)
        self.time_box.setObjectName("time_box")


        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(1630, 770, 221, 71))
        self.exit.setStyleSheet("background-image: url(./Media/exit_btn.png);\n"
        "border:none;")
        self.exit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.exit.setText("")
        self.exit.setProperty("pixmap", QtGui.QPixmap(":/rec/Media/exit_btn.png"))
        self.exit.setProperty("scaledContents", True)
        self.exit.setProperty("wordWrap", False)
        self.exit.setObjectName("exit")


        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1360, 720, 201, 81))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")


        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(360, 720, 201, 81))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")


        self.init_system = QtWidgets.QLabel(Form)
        self.init_system.setGeometry(QtCore.QRect(60, 60, 581, 181))
        self.init_system.setText("")
        self.init_system.setPixmap(QtGui.QPixmap("Media/initializing system.gif"))
        self.init_system.setScaledContents(True)
        self.init_system.setObjectName("init_system")

        self.movie2 = QMovie("./Media/initializing system.gif")
        self.init_system.setMovie(self.movie2)
        self.movie2.start()


        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(700, 727, 531, 61))
        self.time.setText("")
        self.time.setObjectName("time")
        self.time.setAlignment(Qt.AlignCenter)

        


        self.date = QtWidgets.QLabel(Form)
        self.date.setGeometry(QtCore.QRect(140, 280, 251, 41))
        self.date.setObjectName("date")
        self.date.setAlignment(Qt.AlignCenter)



        self.temp = QtWidgets.QLabel(Form)
        self.temp.setGeometry(QtCore.QRect(140, 448, 251, 41))
        self.temp.setObjectName("temp")
        self.temp.setAlignment(Qt.AlignCenter)


        self.arc_side1 = QtWidgets.QLabel(Form)
        self.arc_side1.setGeometry(QtCore.QRect(420, 180, 331, 451))
        self.arc_side1.setText("")
        self.arc_side1.setPixmap(QtGui.QPixmap("Media/arc_side1.jpg"))
        self.arc_side1.setScaledContents(True)
        self.arc_side1.setObjectName("arc_side1")


        self.arc_side2 = QtWidgets.QLabel(Form)
        self.arc_side2.setGeometry(QtCore.QRect(1160, 180, 331, 451))
        self.arc_side2.setText("")
        self.arc_side2.setPixmap(QtGui.QPixmap("Media/arc_side2.jpg"))
        self.arc_side2.setScaledContents(True)
        self.arc_side2.setObjectName("arc_side2")


        self.init_system2 = QtWidgets.QLabel(Form)
        self.init_system2.setGeometry(QtCore.QRect(1280, 60, 581, 181))
        self.init_system2.setText("")
        self.init_system2.setPixmap(QtGui.QPixmap("Media/initializing system.gif"))
        self.init_system2.setScaledContents(True)
        self.init_system2.setObjectName("init_system2")

        self.movie3 = QMovie("./Media/initializing system.gif")
        self.init_system2.setMovie(self.movie2)
        self.movie3.start()


        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(690, 860, 541, 101))
        self.name.setObjectName("name")


        self.label_ip = QtWidgets.QLabel(Form)
        self.label_ip.setGeometry(QtCore.QRect(140, 620, 251, 41))
        self.label_ip.setObjectName("label_ip")
        self.label_ip.setAlignment(Qt.AlignCenter)

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1530, 280, 251, 41))
        self.label_2.setObjectName("label_2")


        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(1530, 450, 251, 41))
        self.label_7.setObjectName("label_7")


        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(1530, 620, 251, 41))
        self.label_8.setObjectName("label_8")


        self.background.raise_()
        self.Frame.raise_()
        self.date_box.raise_()
        self.temperature_box.raise_()
        self.ip_box.raise_()
        self.chat_box.raise_()
        # self.box5.raise_()
        # self.box6.raise_()
        self.time_box.raise_()
        self.exit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.init_system.raise_()
        self.time.raise_()
        self.date.raise_()
        self.temp.raise_()
        self.arc_reactor.raise_()
        self.arc_side1.raise_()
        self.init_system2.raise_()
        self.arc_side2.raise_()
        self.name.raise_()
        self.label_ip.raise_()
        # self.label_2.raise_()
        # self.label_7.raise_()
        # self.label_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Gideon")
        self.date.setText(_translate("Form", "TextLabel"))
        self.temp.setText(_translate("Form", "TextLabel"))
        self.name.setText(_translate("Form", "TextLabel"))
        self.label_ip.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "TextLabel"))
import rec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
